version: "3"

networks:
  chat:
    driver: bridge

services:
  server:
    restart: always
    container_name: server
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - "./:/usr/src/app"
    networks:
      - chat
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - chat
  mongo-express:
    image: mongo-express
    container_name: db_gui
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    networks:
      - chat